payment:
  vnpay:
    tmn-code:
    secret-key:
    init-payment-url:
    return-url:
    timeout:

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

#spring:
#  profiles:
#    active: prod

open:
  api:
    title: API document
    version: v1.0.0.0
    description: API booking hotel system
    serverUrl: http://localhost:9192
    serverName: server test

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_NAME_EMAIL}
    password: ${PASSWORD_EMAIL}
    mail:
        smtp:
          auth: true
          starttls:
            enable: true

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    cache-enabled: true
