package com.example.BookingHotel.constant;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ResponseCode {
    SUCCESS("SUCCESS", 200),
    CHECKIN_DATE_INVALID("CHECKIN_DATE_INVALID",400),
    TOTAL_NUMBER_GUEST_INVALID("TOTAL_NUMBER_GUEST_INVALID",400),
    ERROR_SYSTEM("ERROR_SYSTEM", 400),
    ROOM_EMPTY_INVALID("ROOM_EMPTY_INVALID", 400),
    BOOKED_ROOM_INVALID("BOOKED_ROOM_INVALID", 400),
    CONFLICTED_ROOM("CONFLICT_ROOM", 400),
    ROOM_NOT_FOUND("ROOM_NOT_CONFLICT", 400),
    VNPAY_SIGNIN_FAILED("VNPAY_SIGNIN_FAILED", 400),
    BOOKING_NOT_FOUND("BOOKING_NOT_FOUND", 400),
    LIST_HOTEL_IS_EMPTY("LIST_HOTEL_IS_EMPTY", 400),
    IMAGE_IS_EMPTY("IMAGE_IS_EMPTY", 400),
    USER_NOT_FOUND("USER_NOT_FOUND", 404),
    LIST_ROOM_IS_EMPTY("LIST_ROOM_IS_EMPTY", 400),
    HOTEL_NOT_FOUND("HOTEL_NOT_FOUND", 404),
    CITY_NOT_FOUND("CITY_NOT_FOUND", 404 ),
    DATABASE_ERROR("DATABASE_ERROR", 500 ),
    FILE_PROCESSING_ERROR("FILE_PROCESSING_ERROR", 500),
    ROLE_NOT_EXSIT("ROLE_NOT_EXSIT", 404 ),
    INVALID_AUTHORIZATION_HEADER("INVALID_AUTHORIZATION_HEADER", 400),
    REFRESH_TOKEN_NOT_FOUND("REFRESH_TOKEN_NOT_FOUND",404),
    SEND_EMAIL_FAILED("SEND_EMAIL_FAILED", 400),
    OTP_NOT_EXISTED_OR_VERIFIED("OTP_NOT_EXISTED_OR_VERIFIED", 400),
    CITY_HAVE_NOT_HOTEL("CITY_HAVE_NOT_HOTEL", 404);

    private final String message;
    private final Integer code;
}
